name: Publish .NET Core binaries

on:
  push:
    branches:
      - main
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  release_and_publish:
    name: Create release and publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: ["x64", "arm64"]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: windows-latest
            target_os: windows
          - os: macos-latest
            target_os: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "::set-env name=COMMIT_MESSAGE::$COMMIT_MESSAGE"
          
      - name: Build
        shell: bash
        run: |
          if [[ "${{ matrix.target_os }}" == "macos" && "${{ matrix.arch }}" == "arm64" ]]; then
            # No support for arm64 build using macos
            exit 0;
          fi
          
          version=${{ github.run_number }}
          target_os_filename="${{ matrix.target_os }}-${{ matrix.arch }}"
          release_name_standalone="jsunmap-$version-standalone-$target_os_filename"
          release_name="jsunmap-$version-#target_os_filename"
          target_arch=""
          if [[ "${{ matrix.target_os }}" == "windows" ]]; then
            target_arch="win-${{ matrix.arch }}"
          elif [[ "${{ matrix.target_os }}" == "linux" ]]; then
            target_arch="linux-${{ matrix.arch }}"
          elif [[ "${{ matrix.target_os }}" == "macos" ]]; then
            target_arch="osx-${{ matrix.arch }}"
          fi

          dotnet restore ./src/jsunmap.sln
          dotnet build ./src/jsunmap.sln --configuration Release /p:WarningLevel=0

          echo "Arch: $target_arch - ${{ matrix.arch  }}"
          echo "Self contained: $release_name_standalone"
          
          # Self contained
          dotnet publish ./src/jsunmap.csproj --configuration Release --self-contained --runtime "$target_arch" -o "$release_name_standalone"
          
          echo "Framework dependant: $release_name"
          # Framework dependant
          dotnet publish ./src/jsunmap.csproj --configuration Release --self-contained false --runtime "$target_arch" -o "$release_name"

          if [ "${{ matrix.target_os }}" == "windows" ]; then
            # Pack for standalone version
            7z a -tzip "${release_name_standalone}.zip" "./${release_name_standalone}/*"
            
            # Pack for Framework dependant version
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name_standalone}.tar.gz" "$release_name_standalone"
            
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          rm -r "$release_name_standalone"
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "jsunmap-*"
      
