name: Publish .NET Core binaries

on:
  push:
    branches:
      - main
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  release_and_publish:
    name: Create release and publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: ['x64', 'arm64']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "::set-env name=COMMIT_MESSAGE::$COMMIT_MESSAGE"
          
      - name: Build
        shell: bash
        run: |
          version=${{ github.run_number }}
          release_name_standalone="jsunmap-$version-${{ matrix.target_os }}-${{ matrix.arch }}-standalone"
          release_name="jsunmap-$version-${{ matrix.target_os }}-${{ matrix.arch }}-standalone"
          target_arch=""
          if [[ "${{ matrix.target_os }}" == "windows" ]]; then
            target_arch="win-${{ matrix.arch }}"
          elif [[ "${{ matrix.target_os }}" == "linux" ]]; then
            target_arch="linux-${{ matrix.arch }}"
          elif [[ "${{ matrix.target_os }}" == "mac" ]]; then
            target_arch="osx-${{ matrix.arch }}"
          fi

          # Self contained
          dotnet publish ./src/jsunmap.csproj --configuration Release --self-contained --runtime "$target_arch" -o "$release_name_standalone" -p:PublishTrimmed=true

          # Framework dependant
          dotnet publish ./src/jsunmap.csproj --configuration Release --self-contained false --runtime "$target_arch" -o "$release_name" -p:PublishTrimmed=false

          if [ "${{ matrix.target_os }}" == "windows" ]; then
            # Pack for standalone version
            7z a -tzip "${release_name_standalone}.zip" "./${release_name_standalone}/*"
            
            # Pack for Framework dependant version
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name_standalone}.tar.gz" "$release_name_standalone"
            
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          rm -r "$release_name_standalone"
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "jsunmap-*"
      
